### ISSUE TITLE
Feedback details has no submit button + text change

### ISSUE THREAD

**Issue by hadiasghari** [fhewett/simba#8]
This issue is related to the Firefox store version of the plugin (which I checked). 

- When down-voting the summary, it asks for what text we would like to have highlighted instead, but there is no send/submit button (screen shots available if needed)
- Additionally, the instruction states "Paste sentence you would have prefered to see highlighted.". There is a typo here (preferred); but also, the instruction should be a bit broader (e.g., "Please explain your feedback and/or paste the sentences that would make a better summary)

**Comment by rurfy** [comment]
This is not just an Issue in the API version, I'll look into it
